spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8000
logging:
  group:
    trace: ru.neoflex.conveyor, ru.neoflex.service, ru.neoflex.utils
  level:
    trace: TRACE